# Generated by Django 5.2 on 2025-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_complaint_cad_date_complaint_updated_order_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='case_category',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='mastersetting',
            name='category',
            field=models.CharField(choices=[('Channel', 'Channel'), ('Country', 'Country'), ('Reported By', 'Reported By'), ('Type', 'Type'), ('Series', 'Series'), ('Material', 'Material'), ('Region', 'Region')], max_length=50),
        ),
    ]
