# Generated by Django 5.2 on 2025-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_complaint_case_category_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmedia',
            name='file',
            field=models.CharField(),
        ),
    ]
