# Generated by Django 5.2 on 2025-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_complaintmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
