# Generated by Django 5.2 on 2025-06-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='case_category',
        ),
        migrations.AlterField(
            model_name='mastersetting',
            name='category',
            field=models.CharField(choices=[('Channel', 'Channel'), ('Country', 'Country'), ('Reported By', 'Reported By'), ('Type', 'Type'), ('Series', 'Series'), ('Material', 'Material'), ('Region', 'Region')], max_length=50),
        ),
    ]
